### ISSUE TITLE
Azure DevOps Causes a Differing Behavior (Start-Process)

### ISSUE THREAD

**Issue by Silvenga** [PowerShell/PowerShell#11405]
I was asked by the Azure DevOps support team (case `119110624002446`) to open this bug as it was believed that this is a bug in PowerShell Core, and not Azure DevOps.

# Steps to reproduce

Given a `azure-pipeline.yaml`

```yaml
jobs:
- job: HelloWorld
  pool:
    vmImage: ubuntu-latest
  steps:
  - powershell: |
      Start-Process "tail" -Args "-f /dev/null" 
      exit 0
    timeoutInMinutes: 1
```

# Expected behavior

The task should not timeout.

When executed from a local Ubuntu machine:

```
~$ pwsh
PS> Start-Process "tail" -Args "-f /dev/null"
PS> ps
   PID TTY          TIME CMD
31187 pts/0    00:00:00 bash
31236 pts/0    00:00:02 pwsh
31398 pts/0    00:00:00 tail
31404 pts/0    00:00:00 ps
PS> exit
~$ ps
   PID TTY          TIME CMD
31187 pts/0    00:00:00 bash
31398 pts/0    00:00:00 tail
31423 pts/0    00:00:00 ps
```

The main process (pwsh) does complete and the tail process's parent becomes init:

```
~$ pstree -s -p 31398
systemd(1)───tail(31398)
```

Which is desired behavior.

# Actual behavior

The script exists with exit code 0, and then the task times out waiting for the pwsh process to stop (assumed).

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.15.0-1064-azure #69-Ubuntu SMP Tue Nov …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
