### ISSUE TITLE
Calling Register-PSRepository or Set-PSRepository triggers the error Unknown Option: -V in Powershell Core running on Ubuntu Linux

### ISSUE THREAD

**Issue by tristanbarcelon** [PowerShell/PowerShell#16064]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Create an Azure Devops YAML pipeline with following definition. To protect my private Nuget v2 feed, I've replaced the actual feed url with **myorg** and **myfeed**

```yaml
trigger: none

pool:
   vmImage: 'ubuntu-latest'

variables:
- name: PowershellRepositoryName
  value: 'PrivatePSGallery'
- name: PowershellRepositorySourceLocation
  value: 'https://pkgs.dev.azure.com/**myorg**/_packaging/**myfeed**/nuget/v2'

- task: PowerShell@2
  displayName: 'Set or register PrivatePSGallery'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)/src/setprivatepsgallery.ps1'
    arguments: '-RepositoryName $(PowershellRepositoryName) -RepositorySourceLocation $(PowershellRepositorySourceLocation)'
    failOnStderr: true
    showWarnings: true
    pwsh: true
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```

2. define setprivatepsgallery.ps1 as follows and store in in src folder:

```powershell
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, HelpMessage = 'Powershell repository name to set or register')]
    [string] $RepositoryName,
    [Parameter(Mandatory = $true, HelpMessage = 'Azure Devops feed URL to use as repository source')]
    [string] $RepositorySourceLocation
)
begin {}
process {
    try
    {
        [string] $BuildDefinition = $ENV:BUILD_DEFINITIONNAME

        if ([string]::IsNullOrEmpty($ENV:SYSTEM_ACCESSTOKEN))
        {
            Write-Error "Build pipeline: $BuildDefinition needs to have access to SYSTEM_ACCESSTOKEN environment variable"
        }
        else
        {
            $AZDOCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList @('buildagent', (ConvertTo-SecureString -String $ENV:SYSTEM_ACCESSTOKEN -AsPlainText -Force))
        }

        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13

        Write-Host "Searching for repository: $($RepositoryName)"
        $PrivateRepository = Get-PSRepository -Name $RepositoryName -ErrorAction SilentlyContinue

        if ($null -eq $PrivateRepository)
        {
            $PrivateRepository = Get-PSRepository | Where-Object { ($_.SourceLocation -ieq $RepositorySourceLocation) -and ($_.Name -ine $RepositoryName) }
            if ($null -ne $PrivateRepository)
            {
                Write-Host "Unregistering repository $($RepositoryName)"
                Unregister-PSRepository -Name $RepositoryName
            }
            Write-Host "Registering repository $($RepositoryName) name with SourceLocation to $($RepositorySourceLocation)"
            Register-PSRepository -Name $RepositoryName -SourceLocation $RepositorySourceLocation -InstallationPolicy Trusted -Credential $AZDOCredential
        }
        else
        {
            if (($PrivateRepository.SourceLocation -ine $RepositorySourceLocation) -or ($PrivateRepository.InstallationPolicy -ine 'Trusted'))
            {
                Write-Host "Updating repository $($RepositoryName) because its InstallationPolicy and SourceLocation do not match expected values"
                Set-PSRepository -Name $RepositoryName -InstallationPolicy Trusted -SourceLocation $RepositorySourceLocation -Credential $AZDOCredential
            }
            else
            {
                Write-Host "Found repository: $($RepositoryName) and no updates are needed"
            }
        }
    }
    catch {
        throw $_
    }
    finally {
        Get-Variable -Scope local -ErrorAction SilentlyContinue | Remove-Variable -ErrorAction SilentlyContinue
    }
}
end {}
```

Somebody also mentioned in a [PowershellGetV2 issue](https://github.com/PowerShell/PowerShellGetv2/issues/619) that they also see the "Unknown option: -V" error.

### Expected behavior

```console
I expect it to create or update a repository named PrivatePSGallery on Ubuntu machines 18.04.* or 20.04.* using Powershell Core 7.1.x, 7.0.x releases.
```

### Actual behavior

```console
I get an error like this:


Searching for repository: PrivatePSGallery
Registering repository PrivatePSGallery name with SourceLocation to https://pkgs.dev.azure.com/**myorg**/_packaging/**myfeed**/nuget/v2
Unknown option: -V
.NET SDK (5.0.400)
Usage: dotnet [runtime-options] [path-to-application] [arguments]
```

### Error details

```console
I get an error like this:


Searching for repository: PrivatePSGallery
Registering repository PrivatePSGallery name with SourceLocation to https://pkgs.dev.azure.com/**myorg**/_packaging/**myfeed**/nuget/v2
Unknown option: -V
.NET SDK (5.0.400)
Usage: dotnet [runtime-options] [path-to-application] [arguments]
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Linux 4.15.0-154-generic #161-Ubuntu SMP Fri Jul 30 13:04:17 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
