### ISSUE TITLE
Get-ADUser throws "the encryption operation failed" on latest PowerShell 7.4-preview.5 daily build

### ISSUE THREAD

**Issue by kborowinski** [PowerShell/PowerShell#20168]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

This fails on PowerShell 7.4.0-preview.5 daily build:
```powershell
Get-ADUser -Filter {SamAccountName -like "*test*"}
```
*(This works on PowerShell 7.3.6 and PowerShell 5.1, and the AD sever is NOT down, contrary to the error message)*

### Expected behavior

```console
Should return requested AD user objects
```

### Actual behavior

```console
Throws an exception "the encryption operation failed"
```

### Error details

```console
See visuals
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.5
PSEdition                      Core
GitCommitId                    7.4.0-preview.5-19-gab5213e4b6ea4ac3ba0b84378ed1f31f6e14619c
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0, 7.0}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

![image](https://github.com/PowerShell/PowerShell/assets/16168755/0b16959f-c26b-48a1-899a-3bdd3e03b388)

![ad_error_2](https://github.com/PowerShell/PowerShell/assets/16168755/4961fb9d-33ec-43f0-9a1f-a5830c54ece9)

**Comment by santisq** [comment]
It's not working for me either, different error tho but it confirms it is clearly a `preview` issue:

![image](https://github.com/PowerShell/PowerShell/assets/23342410/1d4b8c50-f64d-4aa8-91d1-61ae17b85ee2)

**Comment by SteveL-MSFT** [comment]
Unfortunately, this appears like a change in .NET that broke the module.  It also seems that the Windows 11 build I have doesn't have the RSAT feature to install this module so I can't debug it.

**Comment by jborean93** [comment]
I've tested a few permutations and it looks like the problem is only happening when Kerberos auth is used. Running directly on a domain controller or using `-Server $ipAddr` (which forces NTLM) works just fine. The inner exception is raised with https://github.com/dotnet/runtime/blob/b09764fa7afa036fb382a071834214173951aed8/src/libraries/System.Net.Security/src/System/Net/Security/NegotiateStream.cs#L541 which occurs when the `wrap` operation to encrypt the data has failed. Unfortunately the codebase drops the status code so I'm unable to determine what the actual error was. When tracing the raw SSPI call I can see it is being called with the following:

```yaml
- Function: Secur32.dll!EncryptMessage
  Time: 2023-08-26T00:42:28.3426475+00:00
  ThreadId: 5856
  Arguments:
    Context: 0x25EFC9034A0 - PCtxtHandle
    Qop: 0
    Message:
      Raw: 0x96DD47E5D0 - PSecBufferDesc
      Version: 0
      Count: 2
      BufferPtr: 0x96DD47E580 - PSecBuffer
      Buffers:
      - Type: 0x00000002 - SECBUFFER_TOKEN
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 28
        Raw: 0x25EFC905F18 - Pointer
        Data: "00000000000000000000000000000000000000000000000000000000"
      - Type: 0x00000001 - SECBUFFER_DATA
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x25EFC905F34 - Pointer
        Data: 0C
    MessageSeqNo: 0
- Function: Secur32.dll!EncryptMessage
  Time: 2023-08-26T00:42:28.3708787+00:00
  ThreadId: 5856
  Result: -2146893023
  Info:
    Message:
      Raw: 0x96DD47E5D0 - PSecBufferDesc
      Version: 0
      Count: 2
      BufferPtr: 0x96DD47E580 - PSecBuffer
      Buffers:
      - Type: 0x00000002 - SECBUFFER_TOKEN
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 28
        Raw: 0x25EFC905F18 - Pointer
        Data: "00000000000000000000000000000000000000000000000000000000"
      - Type: 0x00000001 - SECBUFFER_DATA
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x25EFC905F34 - Pointer
        Data: 0C
```

The status code from this trace is `SEC_E_BUFFER_TOO_SMALL 0x80090321 (-2146893023)`. I think it may have been introduced with https://github.com/dotnet/runtime/pull/86948 but I cannot be 100% sure. One thing it looks like it did was change the sec buffers from 3 (token, data, padding) to just 2 (token, data). It may be unrelated at all to that PR but it's worth a look into.

**Comment by jborean93** [comment]
Just as an FYI here is the raw SSPI trace on net7 which does work

```yaml
- Function: Secur32.dll!EncryptMessage
  Time: 2023-08-26T00:50:38.5234255+00:00
  ThreadId: 4100
  Arguments:
    Context: 0x14D0E452048 - PCtxtHandle
    Qop: 0
    Message:
      Raw: 0x28298E520 - PSecBufferDesc
      Version: 0
      Count: 3
      BufferPtr: 0x28298E480 - PSecBuffer
      Buffers:
      - Type: 0x00000002 - SECBUFFER_TOKEN
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 76
        Raw: 0x14D0E4557B4 - Pointer
        Data: "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      - Type: 0x00000001 - SECBUFFER_DATA
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x14D0E455800 - Pointer
        Data: 0C
      - Type: 0x00000009 - SECBUFFER_PADDING
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x14D0E455801 - Pointer
        Data: "00"
    MessageSeqNo: 0
- Function: Secur32.dll!EncryptMessage
  Time: 2023-08-26T00:50:38.5538292+00:00
  ThreadId: 4100
  Result: 0
  Info:
    Message:
      Raw: 0x28298E520 - PSecBufferDesc
      Version: 0
      Count: 3
      BufferPtr: 0x28298E480 - PSecBuffer
      Buffers:
      - Type: 0x00000002 - SECBUFFER_TOKEN
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 60
        Raw: 0x14D0E4557B4 - Pointer
        Data: 050406FF0000001C0000000055712B36A0F1574715ED1C738DF6B9FADEC2594309FDB80958726776F128C3CEC03CB205AD7C3C57C931B7647CC56D12
      - Type: 0x00000001 - SECBUFFER_DATA
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x14D0E455800 - Pointer
        Data: 6D
      - Type: 0x00000009 - SECBUFFER_PADDING
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 0
        Raw: 0x14D0E455801 - Pointer
        Data: ""
```

You can see it has 3 buffers but also the token buffer is 76 bytes long (not 28) which aligns more with what I typically see on Kerberos and explains why it says the buffer is too small. Looking at the wrap code it is using `cbMaxSignature` https://github.com/dotnet/runtime/blob/b09764fa7afa036fb382a071834214173951aed8/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Windows.cs#L440 when in reality I think it needs `cbSecurityTrailer` which is what I use personally. Even the GSSAPI/SSPI interop examples use `cbSecurityTrailer` https://learn.microsoft.com/en-us/windows/win32/secauthn/sspi-kerberos-interoperability-with-gssapi#message-integrity-and-privacy

```c
// Need three descriptors, two for the SSP and
// one to hold the application data. 
in_buf_desc.cBuffers = 3;
in_buf_desc.pBuffers = wrap_bufs;
in_buf_desc.ulVersion = SECBUFFER_VERSION;
wrap_bufs[0].cbBuffer = sizes.cbSecurityTrailer;
wrap_bufs[0].BufferType = SECBUFFER_TOKEN;
wrap_bufs[0].pvBuffer = malloc(sizes.cbSecurityTrailer);

// This buffer holds the application data.
wrap_bufs[1].BufferType = SECBUFFER_DATA;
wrap_bufs[1].cbBuffer = in_buf.cbBuffer;
wrap_bufs[1].pvBuffer = malloc(wrap_bufs[1].cbBuffer);
memcpy(wrap_bufs[1].pvBuffer, in_buf.pvBuffer, in_buf.cbBuffer);
wrap_bufs[2].BufferType = SECBUFFER_PADDING;
wrap_bufs[2].cbBuffer = sizes.cbBlockSize;
wrap_bufs[2].pvBuffer = malloc(wrap_bufs[2].cbBuffer);
maj_stat = EncryptMessage(&context,
SignOnly ? KERB_WRAP_NO_ENCRYPT : 0,
&in_buf_desc, 0);

// Send a message to the server.
```

**Comment by filipnavara** [comment]
@jborean93 I think you may be right about the `cbMaxSignature` vs `cbSecurityTrailer`. Unfortunately I have basically no way to test this scenario. Would you be able to test it if I make custom System.Net.Security.dll build?

**Comment by jborean93** [comment]
Sure thing, happy to test it out.

**Comment by filipnavara** [comment]
> Can I ask why you removed the padding buffer?

I wish I could answer but I will have to dig deep down the memory lane. It's been more than a year since I wrote that code, and it was resurrected for .NET 8. It's very much possible that I accidentally copied it from the signing code when restructuring the SecBuffer marshalling logic.

Diff: https://github.com/filipnavara/runtime/commit/5e8e4c89afb7f0d48b25f7ed9a35a0f015a21f00

[System.Net.Security.dll.zip](https://github.com/PowerShell/PowerShell/files/12444722/System.Net.Security.dll.zip)

**Comment by filipnavara** [comment]
Diff: https://github.com/filipnavara/runtime/commit/89f7b2700cba8a9a63b7fb8dfbdb68149777f82e

[System.Net.Security.dll.zip](https://github.com/PowerShell/PowerShell/files/12444725/System.Net.Security.dll.zip)

**Comment by filipnavara** [comment]
...and version with (hopefully) fixed padding:

Diff: https://github.com/filipnavara/runtime/commit/1f0fd9431e75970508dc2983bb974f5d8cdf1db5

[System.Net.Security.dll.zip](https://github.com/PowerShell/PowerShell/files/12444740/System.Net.Security.dll.zip)

**Comment by jborean93** [comment]
Can confirm the changes in your dll now work

![screenshot_2023-08-26-170144](https://github.com/PowerShell/PowerShell/assets/8462645/63110e51-9a8c-406a-9137-caee6bcc5a21)

Looking at the raw SSPI calls I now see

```yaml
- Function: Secur32.dll!EncryptMessage
  Time: 2023-08-26T16:59:53.1049824+10:00
  ThreadId: 7988
  Arguments:
    Context: 0x1EDB4038420 - PCtxtHandle
    Qop: 0
    Message:
      Raw: 0xBFCF5FE860 - PSecBufferDesc
      Version: 0
      Count: 3
      BufferPtr: 0xBFCF5FE6B0 - PSecBuffer
      Buffers:
      - Type: 0x00000002 - SECBUFFER_TOKEN
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 76
        Raw: 0x1EDB403A8E8 - Pointer
        Data: "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      - Type: 0x00000001 - SECBUFFER_DATA
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x1EDB403A934 - Pointer
        Data: 0C
      - Type: 0x00000009 - SECBUFFER_PADDING
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x1EDB403A935 - Pointer
        Data: "00"
    MessageSeqNo: 0
- Function: Secur32.dll!EncryptMessage
  Time: 2023-08-26T16:59:53.1337551+10:00
  ThreadId: 7988
  Result: 0
  Info:
    Message:
      Raw: 0xBFCF5FE860 - PSecBufferDesc
      Version: 0
      Count: 3
      BufferPtr: 0xBFCF5FE6B0 - PSecBuffer
      Buffers:
      - Type: 0x00000002 - SECBUFFER_TOKEN
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 60
        Raw: 0x1EDB403A8E8 - Pointer
        Data: 050406FF0000001C00000000680D287489943F5DB7574A80DE16FDBDD535058A21F70CA60CA284A1508723773A512CF961DC1AB2FDCEBE14135D9EA0
      - Type: 0x00000001 - SECBUFFER_DATA
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 1
        Raw: 0x1EDB403A934 - Pointer
        Data: ED
      - Type: 0x00000009 - SECBUFFER_PADDING
        Flags: 0x00000000 - SECBUFFER_NONE
        Size: 0
        Raw: 0x1EDB403A935 - Pointer
        Data: ""
```

This lines up with what I saw previously in net7 so the changes seem good.

Thanks for the quick turnaround, love your work!
